### ISSUE TITLE
PoolComponent is missing

### ISSUE THREAD

**Issue by sectore** [andbet39/Angular2Test#1]
Andrea,

nice example of using Angular2 and TypeScript! 

It seems that `PoolComponent` and its `*.ts` file (`pool.ts`) are missing. The compiled `pool.js` is already there...

-Jens

**Comment by andbet39** [comment]
The pool.js is just a effuse of what i was trying ti do with multiple component.
Pool component is not needed for this example

**Comment by andbet39** [comment]
Take a look on codetutorial.io for complete tutorial

**Comment by sectore** [comment]
`PoolComponent` is still declared as a Directive of `PoolApp` https://github.com/andbet39/Angular2Test/blob/master/poolapp.ts#L20 

Just fyi... ;)
